#include "core/aero_loads.h"
#include "core/fluid/amr_advection.h"
#include "core/fluid/amr_fields.h"
#include "core/fluid/amr_eb.h"
#include "core/fluid/amr_exchange.h"
#include "core/fluid/amr_grid.h"
#include "core/fluid/amr_pressure.h"
#include "core/fluid/eb_pressure.h"
#include "core/fluid/external_aero_core.h"
#include "core/geometry/embedded_boundary.h"
#include "core/geometry/model_placement.h"
#include "core/geometry/triangle_bvh.h"
#include "core/paraglider_config.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <filesystem>
#include <queue>
#include <string>
#include <vector>

#include <cuda_runtime.h>

using namespace paracfd::core;

namespace
{
	int failures=0;
	void check(bool ok,const char* name){std::printf("[paraglider] %-44s %s\n",name,ok?"PASS":"FAIL");if(!ok)++failures;}
	bool near(double a,double b,double tol=1e-8){return std::abs(a-b)<=tol*std::max({1.0,std::abs(a),std::abs(b)});}

	TriMesh mesh_from_quads(const std::vector<std::array<Vec3d,4>>& quads)
	{
		TriMesh m;float lo[3]={1e30f,1e30f,1e30f},hi[3]={-1e30f,-1e30f,-1e30f};
		for(std::size_t q=0;q<quads.size();++q)
		{
			const std::uint32_t base=static_cast<std::uint32_t>(m.vertex_count());
			for(Vec3d p:quads[q]){m.positions.insert(m.positions.end(),{(float)p.x,(float)p.y,(float)p.z});for(int c=0;c<3;++c){lo[c]=std::min(lo[c],(float)p[c]);hi[c]=std::max(hi[c],(float)p[c]);}}
			m.indices.insert(m.indices.end(),{base,base+1,base+2,base,base+2,base+3});m.source_face_ids.push_back((std::uint32_t)q);m.source_face_ids.push_back((std::uint32_t)q);
		}
		m.bbox_min={lo[0],lo[1],lo[2]};m.bbox_max={hi[0],hi[1],hi[2]};return m;
	}
	TriMesh flat_x(double x=0.5){return mesh_from_quads({{{{x,0,0},{x,1,0},{x,1,1},{x,0,1}}}});}
	TriMesh reversed(TriMesh m){for(std::size_t i=0;i<m.indices.size();i+=3)std::swap(m.indices[i+1],m.indices[i+2]);return m;}

	EmbeddedBoundary make_eb(const TriMesh& m,UniformEbGrid g={{0,0,0},1,1,1,1.0}){TriangleBvh b(m);return build_embedded_boundary(m,b,g);}

	bool connected(const EmbeddedBoundary& eb,FragmentRef begin,FragmentRef target)
	{
		std::vector<FragmentRef> todo{begin},seen;while(!todo.empty()){FragmentRef a=todo.back();todo.pop_back();if(a==target)return true;if(std::find(seen.begin(),seen.end(),a)!=seen.end())continue;seen.push_back(a);for(const auto& c:eb.connections){if(c.fragment_a==a)todo.push_back(c.fragment_b);else if(c.fragment_b==a)todo.push_back(c.fragment_a);}}return false;
	}
	bool project_composite_flux_case(const CompositeAmrPressureSystem& system,const AmrHierarchy& hierarchy,bool embedded_case,const char* label)
	{
		AmrHostFields host_fields(hierarchy);CompositeAmrFluxes initial_flux=make_zero_composite_fluxes(system);if(embedded_case){if(initial_flux.embedded_velocity.empty())return false;initial_flux.embedded_velocity.front()=0.2;}else{if(initial_flux.coarse_fine_velocity.empty())return false;initial_flux.coarse_fine_velocity.front()=0.2;}
		std::vector<double> cpu_before;composite_amr_divergence_cpu(system,host_fields,initial_flux,cpu_before);DeviceAmrFields device_fields(hierarchy);device_fields.upload(host_fields);DeviceCompositeAmrProjection projection(system,device_fields);projection.upload_special_fluxes(initial_flux);projection.compute_divergence();std::vector<Real> gpu_before;projection.download_divergence(gpu_before);
		double before_error=0,before_scale=1;for(std::size_t q=0;q<gpu_before.size();++q){before_error=std::max(before_error,std::abs(static_cast<double>(gpu_before[q])-cpu_before[q]));before_scale=std::max(before_scale,std::abs(cpu_before[q]));}
		AmrGpuSolveResult result=projection.project(Real(1.225),Real(0.01),sizeof(Real)==4?1e-5:1e-10,1000,false);std::vector<Real> gpu_after,pressure_real;projection.download_divergence(gpu_after);projection.download_pressure(pressure_real);CompositeAmrFluxes gpu_flux;projection.download_special_fluxes(gpu_flux);
		std::vector<double> pressure(pressure_real.size());for(std::size_t q=0;q<pressure.size();++q)pressure[q]=pressure_real[q];AmrHostFields cpu_fields(hierarchy);CompositeAmrFluxes cpu_flux=initial_flux;composite_amr_correct_fluxes_cpu(system,pressure,1.225,0.01,cpu_fields,cpu_flux);std::vector<double> cpu_after;composite_amr_divergence_cpu(system,cpu_fields,cpu_flux,cpu_after);
		double d0=0,d1=0,after_error=0,after_scale=1,flux_error=0;for(double value:cpu_before)d0=std::max(d0,std::abs(value));for(std::size_t q=0;q<gpu_after.size();++q){d1=std::max(d1,std::abs(static_cast<double>(gpu_after[q])));after_error=std::max(after_error,std::abs(static_cast<double>(gpu_after[q])-cpu_after[q]));after_scale=std::max(after_scale,std::abs(cpu_after[q]));}for(std::size_t q=0;q<cpu_flux.coarse_fine_velocity.size();++q)flux_error=std::max(flux_error,std::abs(cpu_flux.coarse_fine_velocity[q]-gpu_flux.coarse_fine_velocity[q]));for(std::size_t q=0;q<cpu_flux.embedded_velocity.size();++q)flux_error=std::max(flux_error,std::abs(cpu_flux.embedded_velocity[q]-gpu_flux.embedded_velocity[q]));
		std::printf("[paraglider] %s GPU-native projection max-divergence %.3e -> %.3e (%d iterations), CPU parity %.3e/%.3e\n",label,d0,d1,result.iterations,before_error/before_scale,after_error/after_scale);return result.converged&&before_error/before_scale<(sizeof(Real)==4?2e-6:1e-12)&&after_error/after_scale<(sizeof(Real)==4?3e-5:1e-11)&&flux_error<(sizeof(Real)==4?2e-6:1e-12)&&d1<std::max(1e-8,d0*(sizeof(Real)==4?3e-4:1e-8));
	}
}

int main()
{
	ParagliderConfig saved_config;saved_config.step_path="wing.step";saved_config.placement.tx=1.25;saved_config.placement.m[1]=-1;saved_config.placement.m[3]=1;saved_config.freestream.speed=12.5;saved_config.amr.brick_size=16;saved_config.amr.min_aperture_area_fraction=2e-4;saved_config.reference.area=24.0;const std::filesystem::path config_path=std::filesystem::temp_directory_path()/(sizeof(Real)==4?"paracfd-config-fp32.json":"paracfd-config-fp64.json");std::string config_error;ParagliderConfig loaded_config;const bool config_saved=save_paraglider_config(config_path.string(),saved_config,&config_error),config_loaded=config_saved&&load_paraglider_config(config_path.string(),loaded_config,&config_error);std::error_code remove_error;std::filesystem::remove(config_path,remove_error);check(config_loaded&&loaded_config.step_path==saved_config.step_path&&near(loaded_config.placement.tx,1.25)&&near(loaded_config.placement.m[1],-1)&&near(loaded_config.freestream.speed,12.5)&&loaded_config.amr.brick_size==16&&near(loaded_config.amr.min_aperture_area_fraction,2e-4)&&near(loaded_config.reference.area,24.0),"paraglider JSON configuration round-trip");
	// BVH: exact cell query, two-sided segment crossing, and nearest-distance result.
	TriMesh flat=flat_x();TriangleBvh bvh(flat);Aabb3d hitbox{{0.49,0.2,0.2},{0.51,0.8,0.8}},missbox{{0.0,0.2,0.2},{0.4,0.8,0.8}};
	check(bvh.query_aabb(hitbox).size()==2&&bvh.query_aabb(missbox).empty(),"BVH exact AABB query");
	TriMesh span_x;span_x.bbox_min={-5,-1,-0.5f};span_x.bbox_max={5,1,0.5f};const HorizontalWingAxes axes_x=infer_horizontal_wing_axes(span_x);TriMesh span_y;span_y.bbox_min={-1,-5,-0.5f};span_y.bbox_max={1,5,0.5f};const HorizontalWingAxes axes_y=infer_horizontal_wing_axes(span_y);TriMesh ambiguous;ambiguous.bbox_min={-1,-1,-0.5f};ambiguous.bbox_max={1,1,0.5f};check(axes_x.valid&&axes_x.span_axis==0&&axes_x.chord_axis==1&&near(axes_x.yaw_degrees,-90)&&axes_y.valid&&axes_y.span_axis==1&&axes_y.chord_axis==0&&near(axes_y.yaw_degrees,0)&&!infer_horizontal_wing_axes(ambiguous).valid,"face bbox infers span/chord axes but not LE/TE polarity");
	const ModelPlacement framed=frame_wing_for_external_domain(flat,ModelPlacement{},3,2,2,4);const TriMesh framed_flat=placed_mesh(flat,framed);check(near(framed_flat.bbox_min[0],3)&&near(framed_flat.bbox_min[1],3.5)&&near(framed_flat.bbox_max[1],4.5)&&near(framed_flat.bbox_min[2],3.5)&&near(framed_flat.bbox_max[2],4.5),"GUI and probes share one zero-origin external-domain frame");
	SegmentHit sh=bvh.intersect_segment({0,0.3,0.4},{1,0.3,0.4});check(sh.hit&&near(sh.t,0.5,1e-12),"BVH two-sided segment intersection");
	auto np=bvh.nearest({0.2,0.3,0.4});check(np.found&&near(np.distance,0.3,1e-12),"BVH nearest surface / distance");
	TriMesh placement_source=flat;placement_source.normals.assign(placement_source.positions.size(),0);for(std::size_t v=0;v<placement_source.vertex_count();++v)placement_source.normals[3*v]=1;placement_source.vertex_uv.assign(2*placement_source.vertex_count(),0.25f);ModelPlacement reflected;reflected.m[0]=-1;TriMesh placement_mesh=placed_mesh(placement_source,reflected);check(placement_mesh.source_face_ids==placement_source.source_face_ids&&placement_mesh.vertex_uv==placement_source.vertex_uv&&near(placement_mesh.normals[0],1.0,1e-7),"placement preserves CAD metadata and winding normal");

	// Flat membrane: two independent fluid CVs, exact patch geometry, no through connection.
	EmbeddedBoundary eb=make_eb(flat);check(eb.ready_for_flow()&&eb.fragments.size()==2&&eb.cells[0].state==EbCellState::split,"flat membrane creates two fluid fragments");
	check(near(eb.fragments[0].volume,0.5,1e-10)&&near(eb.fragments[1].volume,0.5,1e-10),"flat membrane fragment volumes");
	double area=0;Vec3d an{};for(const auto& p:eb.patches){area+=p.area;an=an+p.normal*p.area;}check(near(area,1.0,1e-10)&&near(an.x,1.0,1e-10)&&near(an.y,0)&&near(an.z,0),"flat membrane area and normal");
	check(!connected(eb,eb.fragment_for_side(0,-1),eb.fragment_for_side(0,1)),"no pressure/flux connection through fabric");

	// Inclined analytical cut x+y=1: two half-volume fragments, section area sqrt(2).
	TriMesh inclined=mesh_from_quads({{{{-1,2,-1},{2,-1,-1},{2,-1,2},{-1,2,2}}}});EmbeddedBoundary ie=make_eb(inclined);double ia=0;for(auto& p:ie.patches)ia+=p.area;
	check(ie.ready_for_flow()&&ie.fragments.size()==2&&near(ie.fragments[0].volume,0.5,1e-9)&&near(ie.fragments[1].volume,0.5,1e-9),"inclined membrane analytical volumes");
	check(near(ia,std::sqrt(2.0),1e-9),"inclined membrane analytical area");
	// Several triangles on one gently curved CAD sheet may share a CFD cell. They are
	// conservatively fitted to one local topology plane; this must remain distinct from
	// accepting a rib junction or two nearby skins below.
	TriMesh smooth=mesh_from_quads({{{{0.45,0,0},{0.55,0.5,0},{0.55,0.5,1},{0.45,0,1}}},{{{0.55,0.5,0},{0.45,1,0},{0.45,1,1},{0.55,0.5,1}}}});EmbeddedBoundary smooth_eb=make_eb(smooth);
	check(smooth_eb.ready_for_flow()&&smooth_eb.fragments.size()==2&&smooth_eb.patches.size()==4,"gently curved tessellated sheet gets one bounded local topology plane");

	// Deliberate one-cell opening: opposite sides connect only by travelling through the gap cell.
	TriMesh pieces=mesh_from_quads({{{{0,0,0.5},{1,0,0.5},{1,1,0.5},{0,1,0.5}}},{{{2,0,0.5},{3,0,0.5},{3,1,0.5},{2,1,0.5}}}});UniformEbGrid g3{{0,0,0},3,1,1,1};EmbeddedBoundary oe=make_eb(pieces,g3);
	check(oe.ready_for_flow()&&oe.cells[1].state==EbCellState::regular,"opening remains ordinary fluid (not auto-closed)");
	check(connected(oe,oe.fragment_for_side(0,-1),oe.fragment_for_side(0,1)),"flow connectivity passes around fabric through opening");

	// Multiple sheets in a cell are never collapsed into a fake two-fragment topology.
	TriMesh tj=mesh_from_quads({{{{0.5,0,0},{0.5,1,0},{0.5,1,1},{0.5,0,1}}},{{{0,0.5,0},{1,0.5,0},{1,0.5,1},{0,0.5,1}}}});EmbeddedBoundary te=make_eb(tj);
	check(!te.ready_for_flow()&&te.cells[0].state==EbCellState::unresolved,"rib/T-junction requests refinement");
	EmbeddedBoundaryBuildOptions sampled_options;sampled_options.complex_subdivisions=8;TriangleBvh tj_bvh(tj);EmbeddedBoundary sampled_tj=build_embedded_boundary(tj,tj_bvh,{{0,0,0},1,1,1,1.0},sampled_options);bool valid_tj_patches=true;for(const SurfacePatch& patch:sampled_tj.patches)valid_tj_patches=valid_tj_patches&&patch.plus_fragment!=invalid_fragment&&patch.minus_fragment!=invalid_fragment&&patch.plus_fragment!=patch.minus_fragment;check(sampled_tj.ready_for_flow()&&sampled_tj.fragments.size()==4&&valid_tj_patches,"sampled finest-cell fallback preserves four fluid regions at a membrane junction");
	TriMesh terminating=mesh_from_quads({{{{0.5,0,0},{0.5,0.5,0},{0.5,0.5,1},{0.5,0,1}}}});TriangleBvh terminating_bvh(terminating);EmbeddedBoundary terminating_eb=build_embedded_boundary(terminating,terminating_bvh,{{0,0,0},1,1,1,1.0},sampled_options);check(terminating_eb.ready_for_flow()&&terminating_eb.fragments.size()==1&&!terminating_eb.patches.empty()&&terminating_eb.patches[0].plus_fragment==terminating_eb.patches[0].minus_fragment,"sub-cell fabric edge leaves one fluid region connected around the real opening");
	TriMesh trailing=mesh_from_quads({{{{0,0,0.35},{1,0,0.48},{1,1,0.48},{0,1,0.35}}},{{{0,0,0.65},{1,0,0.52},{1,1,0.52},{0,1,0.65}}}});EmbeddedBoundary tre=make_eb(trailing);
	check(!tre.ready_for_flow(),"thin trailing edge is reported, never joined");

	// Manufactured two-pressure state and reversed winding: plus/minus swap, physical force does not.
	auto pressure_by_world_side=[](const EmbeddedBoundary& x){EbPressureState p;p.regular.assign(x.grid.cell_count(),0);p.irregular.resize(x.fragments.size());for(std::size_t i=0;i<x.fragments.size();++i)p.irregular[i]=x.fragments[i].centroid.x<0.5?2.0:1.0;return p;};
	FreestreamConfig fs;fs.speed=1;fs.rho=2;AeroReferenceConfig ar;ar.area=1;AerodynamicLoads fwd=compute_pressure_loads(eb,pressure_by_world_side(eb),flat.triangle_count(),fs,ar);
	TriMesh rev=reversed(flat);EmbeddedBoundary reb=make_eb(rev);AerodynamicLoads back=compute_pressure_loads(reb,pressure_by_world_side(reb),rev.triangle_count(),fs,ar);
	check(near(fwd.pressure_force.x,1.0,1e-10)&&near(fwd.pressure_force.x,back.pressure_force.x,1e-10)&&near(fwd.pressure_force.y,back.pressure_force.y)&&near(fwd.pressure_force.z,back.pressure_force.z),"pressure force invariant to triangle winding");
	check(fwd.force_coefficients_valid&&near(fwd.cd_pressure,1.0,1e-10),"pressure-only Cp/CD with explicit reference area");
	AeroReferenceConfig no_ref;AerodynamicLoads unscaled=compute_pressure_loads(eb,pressure_by_world_side(eb),flat.triangle_count(),fs,no_ref);check(!unscaled.force_coefficients_valid&&std::isnan(unscaled.cd_pressure),"CL/CD withheld without reference area");

	// Hybrid finite-volume operator: regular stencil + compact aperture work list. Verify
	// conservation, GPU FP32 agreement, and a complete pressure projection on aperture fluxes.
	EbPressureSystem ops=build_eb_pressure_system(oe,false);std::vector<double> pv(ops.storage_size,0),cpu_A;for(int i=0;i<ops.storage_size;++i)if(ops.active[i])pv[i]=0.13*i-0.4;ops.apply_cpu(pv,cpu_A);double asum=0;for(double v:cpu_A)asum+=v;check(std::abs(asum)<1e-11,"Neumann EB pressure operator is conservative");
	std::vector<Real> pf(pv.size()),gpu_A(pv.size());for(std::size_t i=0;i<pv.size();++i)pf[i]=(Real)pv[i];Real *dp=nullptr,*da=nullptr;cudaMalloc(&dp,pf.size()*sizeof(Real));cudaMalloc(&da,pf.size()*sizeof(Real));cudaMemcpy(dp,pf.data(),pf.size()*sizeof(Real),cudaMemcpyHostToDevice);DeviceEbPressureOperator dop(ops);dop.apply(dp,da);cudaMemcpy(gpu_A.data(),da,gpu_A.size()*sizeof(Real),cudaMemcpyDeviceToHost);cudaFree(dp);cudaFree(da);double op_err=0,op_scale=1;for(std::size_t i=0;i<gpu_A.size();++i){op_err=std::max(op_err,std::abs((double)gpu_A[i]-cpu_A[i]));op_scale=std::max(op_scale,std::abs(cpu_A[i]));}std::printf("[paraglider] EB operator %s vs FP64 rel-max = %.3e\n",sizeof(Real)==4?"FP32":"FP64",op_err/op_scale);check(op_err/op_scale<2e-6,sizeof(Real)==4?"FP32 GPU EB operator matches FP64 reference":"FP64 GPU EB operator matches FP64 reference");
	std::vector<Real> br(cpu_A.size()),xs(cpu_A.size());for(std::size_t i=0;i<br.size();++i)br[i]=(Real)cpu_A[i];Real *db=nullptr,*dx=nullptr;cudaMalloc(&db,br.size()*sizeof(Real));cudaMalloc(&dx,xs.size()*sizeof(Real));cudaMemcpy(db,br.data(),br.size()*sizeof(Real),cudaMemcpyHostToDevice);DeviceEbPressureSolver gpu_solver(ops);const double gpu_tol=sizeof(Real)==4?1e-5:1e-10;EbGpuSolveResult gsr=gpu_solver.solve(dx,db,gpu_tol,200,false);std::printf("[paraglider] EB GPU CG iterations=%d relative-residual=%.3e\n",gsr.iterations,gsr.relative_residual);check(gsr.converged&&gsr.relative_residual<gpu_tol*1.1,"GPU-resident EB pressure CG converges");EbGpuSolveResult warm_gsr=gpu_solver.solve(dx,db,gpu_tol,20,true);check(warm_gsr.converged&&warm_gsr.relative_residual<gpu_tol*1.1,"GPU EB pressure warm start uses b - A p");cudaFree(db);cudaFree(dx);
	EbFaceFluxes flux=make_zero_fluxes(oe);if(!flux.aperture_velocity.empty())flux.aperture_velocity[0]=0.2;std::vector<double> rhs,sol(ops.storage_size,0),div0,div1;eb_divergence_cpu(ops,flux,div0);eb_projection_rhs_cpu(ops,flux,1.225,0.01,rhs);EbCpuSolveResult sr=solve_eb_pressure_cpu(ops,rhs,sol,1e-11,500);eb_correct_fluxes_cpu(ops,sol,1.225,0.01,flux);eb_divergence_cpu(ops,flux,div1);double d0=0,d1=0;for(double x:div0)d0=std::max(d0,std::abs(x));for(double x:div1)d1=std::max(d1,std::abs(x));std::printf("[paraglider] EB projection max-divergence %.3e -> %.3e (CPU reference)\n",d0,d1);check(sr.converged&&d1<std::max(1e-10,d0*1e-9),"EB projection removes control-volume divergence");
	EbPressureSystem flat_ops=build_eb_pressure_system(eb,false);EbFaceFluxes blocked=make_zero_fluxes(eb);std::vector<double> blocked_div;eb_divergence_cpu(flat_ops,blocked,blocked_div);double blocked_max=0;for(double x:blocked_div)blocked_max=std::max(blocked_max,std::abs(x));check(eb.apertures.empty()&&blocked_max==0,"impermeable plate has exactly zero fabric flux DOF");
	// A membrane exactly coincident with a Cartesian face is a blocked cut face, not a
	// pair of zero-volume fragments. The otherwise implicit regular stencil/flux is suppressed.
	UniformEbGrid aligned_grid{{0,0,0},2,1,1,1};TriMesh aligned_mesh=flat_x(1.0);EmbeddedBoundary aligned_eb=make_eb(aligned_mesh,aligned_grid);check(aligned_eb.ready_for_flow()&&aligned_eb.fragments.empty()&&aligned_eb.cells[0].state==EbCellState::regular&&aligned_eb.cells[1].state==EbCellState::regular&&(aligned_eb.cut_face_mask[0]&1u),"face-aligned membrane uses blocked face, no tiny fragments");
	EmbeddedBoundaryBuildOptions partial_options;partial_options.complex_subdivisions=8;TriMesh partial_face=mesh_from_quads({{{{1,0.25,0},{1,0.75,0},{1,0.75,1},{1,0.25,1}}}});TriangleBvh partial_face_bvh(partial_face);EmbeddedBoundary partial_face_eb=build_embedded_boundary(partial_face,partial_face_bvh,aligned_grid,partial_options);double partial_open_area=0;for(const FaceAperture& aperture:partial_face_eb.apertures)partial_open_area+=aperture.area;check(partial_face_eb.ready_for_flow()&&(partial_face_eb.cut_face_mask[0]&1u)&&partial_face_eb.apertures.size()==2&&near(partial_open_area,0.5,1e-12),"partially covered aligned face retains two disconnected fluid apertures");
	TriMesh sliver_sheet=mesh_from_quads({{{{0,0.99999,0},{2,0.99999,0},{2,0.99999,1},{0,0.99999,1}}}});TriangleBvh sliver_bvh(sliver_sheet);EmbeddedBoundaryBuildOptions keep_sliver;keep_sliver.min_aperture_area_fraction=0;EmbeddedBoundary unfiltered_sliver=build_embedded_boundary(sliver_sheet,sliver_bvh,aligned_grid,keep_sliver);EmbeddedBoundary filtered_sliver=build_embedded_boundary(sliver_sheet,sliver_bvh,aligned_grid,{});EbPressureSystem filtered_sliver_system=build_eb_pressure_system(filtered_sliver,false);std::vector<double> filtered_sliver_p(filtered_sliver_system.storage_size),filtered_sliver_A;for(int q=0;q<filtered_sliver_system.storage_size;++q)filtered_sliver_p[q]=0.7+0.13*q;filtered_sliver_system.apply_cpu(filtered_sliver_p,filtered_sliver_A);double filtered_sliver_sum=0;for(double value:filtered_sliver_A)filtered_sliver_sum+=value;std::printf("[paraglider] aperture filter retained=%zu/%zu discarded=%zu area=%.12g connections=%zu\n",filtered_sliver.apertures.size(),unfiltered_sliver.apertures.size(),filtered_sliver.discarded_subgrid_apertures,filtered_sliver.discarded_subgrid_aperture_area,filtered_sliver.connections.size());check(unfiltered_sliver.apertures.size()==2&&filtered_sliver.apertures.size()==1&&filtered_sliver.discarded_subgrid_apertures==1&&near(filtered_sliver.discarded_subgrid_aperture_area,1e-5,2e-8)&&filtered_sliver.connections.size()==filtered_sliver.apertures.size()&&std::abs(filtered_sliver_sum)<1e-12,"sub-grid aperture sliver is removed conservatively from flux and pressure graphs with explicit area telemetry");
	EbPressureSystem aligned_ops=build_eb_pressure_system(aligned_eb,false);std::vector<double> aligned_pressure{2.0,1.0},aligned_A;aligned_ops.apply_cpu(aligned_pressure,aligned_A);EbFaceFluxes aligned_flux=make_zero_fluxes(aligned_eb);aligned_flux.x[1]=4.0;std::vector<double> aligned_div;eb_divergence_cpu(aligned_ops,aligned_flux,aligned_div);std::vector<Real> aligned_real{Real(2),Real(1)},aligned_gpu(2);Real *aligned_dp=nullptr,*aligned_da=nullptr;cudaMalloc(&aligned_dp,2*sizeof(Real));cudaMalloc(&aligned_da,2*sizeof(Real));cudaMemcpy(aligned_dp,aligned_real.data(),2*sizeof(Real),cudaMemcpyHostToDevice);DeviceEbPressureOperator aligned_device_op(aligned_ops);aligned_device_op.apply(aligned_dp,aligned_da);cudaMemcpy(aligned_gpu.data(),aligned_da,2*sizeof(Real),cudaMemcpyDeviceToHost);cudaFree(aligned_dp);cudaFree(aligned_da);check(near(aligned_A[0],0)&&near(aligned_A[1],0)&&near(aligned_div[0],0)&&near(aligned_div[1],0)&&near(aligned_gpu[0],0)&&near(aligned_gpu[1],0),"face-aligned fabric suppresses implicit CPU/GPU pressure/flux connection");
	EbPressureState aligned_state;aligned_state.regular={2.0,1.0};AerodynamicLoads aligned_load=compute_pressure_loads(aligned_eb,aligned_state,aligned_mesh.triangle_count(),fs,ar);check(near(aligned_load.pressure_force.x,1.0,1e-10),"face-aligned fabric retains independent two-sided pressure load");
	TriMesh near_face=flat_x(0.98);UniformEbGrid g2{{0,0,0},2,1,1,1};EmbeddedBoundary se=make_eb(near_face,g2);EbPressureSystem ss=build_eb_pressure_system(se,false);int merged=0;for(int fi=0;fi<(int)se.fragments.size();++fi)if(se.fragments[fi].merge_target!=irregular_fragment(fi))++merged;double active_volume=0;for(std::size_t i=0;i<ss.volume.size();++i)if(ss.active[i])active_volume+=ss.volume[i];check(se.ready_for_flow()&&merged==1&&near(active_volume,2.0,1e-10),"small fragment merges conservatively on same side");
	EmbeddedBoundary chain;chain.grid={{0,0,0},1,1,1,1};chain.cells.resize(1);chain.cut_face_mask.assign(1,0);chain.cells[0].state=EbCellState::split;chain.cells[0].first_fragment=0;chain.cells[0].fragment_count=3;chain.fragments={{0,0.01,{0.1,0.5,0.5},-1,irregular_fragment(1)},{0,0.09,{0.2,0.5,0.5},-1,irregular_fragment(2)},{0,0.90,{0.6,0.5,0.5},-1,irregular_fragment(2)}};EbPressureSystem chain_system=build_eb_pressure_system(chain,false);check(chain_system.fragment_dof[0]==chain_system.fragment_dof[1]&&chain_system.fragment_dof[1]==chain_system.fragment_dof[2]&&near(chain_system.volume[chain_system.fragment_dof[2]],1.0,1e-12),"small-fragment merge chains resolve conservatively");
	EmbeddedBoundary static_pocket;static_pocket.grid={{0,0,0},1,1,1,1};static_pocket.cells.resize(1);static_pocket.cut_face_mask.assign(1,0);static_pocket.cells[0].state=EbCellState::split;static_pocket.cells[0].first_fragment=0;static_pocket.cells[0].fragment_count=1;FluidFragment pocket_fragment{0,0.01,{0.5,0.5,0.5},0,irregular_fragment(0),1,0,0};pocket_fragment.pressure_static=true;static_pocket.fragments.push_back(pocket_fragment);EbPressureSystem static_system=build_eb_pressure_system(static_pocket,false);const int static_dof=static_system.fragment_dof[0];check(static_dof>=0&&!static_system.active[static_dof]&&near(static_system.volume[static_dof],0.01),"isolated sealed pocket retains pressure state/volume but is excluded from projection");

	// One-level bricks equal a uniform Cartesian tiling; host and GPU halo paths agree.
	AmrHierarchy uh=AmrHierarchy::uniform({{0,0,0},{8,4,4}},1.0,4,1);check(uh.levels().size()==1&&uh.levels()[0].active_bricks==2&&uh.active_cell_count()==128,"one AMR level equals uniform Cartesian grid");
	TriMesh composite_merge_fabric=mesh_from_quads({{{{3.98,0,0},{3.98,4,0},{3.98,4,4},{3.98,0,4}}}});TriangleBvh composite_merge_bvh(composite_merge_fabric);AmrEmbeddedBoundaryAtlas composite_merge_atlas=build_amr_embedded_boundary_atlas(uh,composite_merge_fabric,composite_merge_bvh);CompositeAmrPressureSystem composite_merge_system=build_composite_amr_pressure_system(uh,composite_merge_atlas,false);double composite_merge_volume=0;bool composite_regular_merge=false,composite_distance_ok=true;for(int q=0;q<composite_merge_system.storage_size;++q)if(composite_merge_system.active[q]){composite_merge_volume+=composite_merge_system.volume[q];if(q<128&&composite_merge_system.volume[q]>1.0001)composite_regular_merge=true;}for(const CoarseFinePressureConnection& edge:composite_merge_system.embedded){const double expected=std::sqrt(length2(composite_merge_system.centroid[edge.coarse_dof]-composite_merge_system.centroid[edge.fine_dof]));composite_distance_ok=composite_distance_ok&&near(edge.centre_distance,expected,1e-12);}check(composite_regular_merge&&near(composite_merge_volume,128.0,1e-11)&&composite_distance_ok,"composite AMR conserves merged EB volume/centroids");
	AmrHierarchy padded=AmrHierarchy::uniform({{0,0,0},{13,15,9}},0.25,32,1);const Aabb3d padded_box=padded.domain();check(near(padded_box.lo.x,0)&&near(padded_box.hi.x,16)&&near(padded_box.lo.y,-0.5)&&near(padded_box.hi.y,15.5)&&near(padded_box.lo.z,-3.5)&&near(padded_box.hi.z,12.5),"base-brick padding is downstream in X and symmetric in Y/Z");
	// The EB atlas uses level-global cells, not one isolated topology per brick. A
	// regular pressure jump therefore couples across x=4, whereas fabric exactly on
	// that same brick interface blocks it while retaining two independent pressures.
	TriMesh no_fabric;TriangleBvh no_fabric_bvh(no_fabric);OneLevelEmbeddedBoundary regular_composite=build_one_level_embedded_boundary(uh,no_fabric,no_fabric_bvh);EbPressureSystem regular_composite_system=build_eb_pressure_system(regular_composite.topology,false);std::vector<double> composite_p(regular_composite_system.storage_size),composite_A;for(int k=0;k<4;++k)for(int j=0;j<4;++j)for(int i=0;i<8;++i)composite_p[regular_composite_system.cell_dof[regular_composite.topology.grid.cell_index(i,j,k)]]=i<4?2.0:1.0;regular_composite_system.apply_cpu(composite_p,composite_A);double regular_interface_abs=0;for(double q:composite_A)regular_interface_abs+=std::abs(q);check(near(regular_interface_abs,32.0,1e-12),"one-level pressure operator connects regular cells across brick interfaces");
	TriMesh interface_fabric=mesh_from_quads({{{{4,0,0},{4,4,0},{4,4,4},{4,0,4}}}});TriangleBvh interface_bvh(interface_fabric);OneLevelEmbeddedBoundary fabric_composite=build_one_level_embedded_boundary(uh,interface_fabric,interface_bvh);EbPressureSystem fabric_composite_system=build_eb_pressure_system(fabric_composite.topology,false);std::vector<double> fabric_p(fabric_composite_system.storage_size),fabric_A;for(int k=0;k<4;++k)for(int j=0;j<4;++j)for(int i=0;i<8;++i)fabric_p[fabric_composite_system.cell_dof[fabric_composite.topology.grid.cell_index(i,j,k)]]=i<4?2.0:1.0;fabric_composite_system.apply_cpu(fabric_p,fabric_A);double blocked_interface_max=0;for(double q:fabric_A)blocked_interface_max=std::max(blocked_interface_max,std::abs(q));check(fabric_composite.ready_for_flow()&&near(blocked_interface_max,0,1e-12)&&(fabric_composite.topology.cut_face_mask[fabric_composite.topology.grid.cell_index(3,1,1)]&1u),"fabric on a brick interface blocks pressure/flux without an artificial brick wall");
	AmrEmbeddedBoundaryAtlas disconnected_atlas=build_amr_embedded_boundary_atlas(uh,interface_fabric,interface_bvh);CompositeAmrPressureSystem disconnected_system=build_composite_amr_pressure_system(uh,disconnected_atlas,true);check(disconnected_system.gauges.size()==1,"pressure projection pins each fluid component disconnected from outlet");std::vector<double> disconnected_pressure(disconnected_system.storage_size),disconnected_cpu;std::vector<Real> disconnected_real(disconnected_system.storage_size),disconnected_gpu(disconnected_system.storage_size);for(int q=0;q<disconnected_system.storage_size;++q)if(disconnected_system.active[q])disconnected_pressure[q]=0.011*q+0.3;disconnected_system.apply_cpu(disconnected_pressure,disconnected_cpu);for(int q=0;q<disconnected_system.storage_size;++q)disconnected_real[q]=static_cast<Real>(disconnected_pressure[q]);Real *disconnected_dp=nullptr,*disconnected_da=nullptr;cudaMalloc(&disconnected_dp,disconnected_real.size()*sizeof(Real));cudaMalloc(&disconnected_da,disconnected_real.size()*sizeof(Real));cudaMemcpy(disconnected_dp,disconnected_real.data(),disconnected_real.size()*sizeof(Real),cudaMemcpyHostToDevice);DeviceCompositeAmrPressureOperator disconnected_device(disconnected_system);disconnected_device.apply(disconnected_dp,disconnected_da);cudaMemcpy(disconnected_gpu.data(),disconnected_da,disconnected_gpu.size()*sizeof(Real),cudaMemcpyDeviceToHost);cudaFree(disconnected_dp);cudaFree(disconnected_da);double disconnected_error=0,disconnected_scale=1;for(int q=0;q<disconnected_system.storage_size;++q){disconnected_error=std::max(disconnected_error,std::abs(static_cast<double>(disconnected_gpu[q])-disconnected_cpu[q]));disconnected_scale=std::max(disconnected_scale,std::abs(disconnected_cpu[q]));}check(disconnected_error/disconnected_scale<(sizeof(Real)==4?3e-6:1e-12),"CUDA composite operator includes disconnected-component gauge");
	TriMesh interior_fabric=mesh_from_quads({{{{3.5,0,0},{3.5,4,0},{3.5,4,4},{3.5,0,4}}}});TriangleBvh interior_bvh(interior_fabric);AmrEmbeddedBoundaryAtlas interior_atlas=build_amr_embedded_boundary_atlas(uh,interior_fabric,interior_bvh);CompositeAmrPressureSystem interior_system=build_composite_amr_pressure_system(uh,interior_atlas,false);const int regular_storage=build_composite_amr_pressure_system(uh,false).storage_size;std::vector<double> interior_pressure(interior_system.storage_size),interior_cpu;for(int q=0;q<interior_system.storage_size;++q)if(interior_system.active[q])interior_pressure[q]=0.017*q-0.2;interior_system.apply_cpu(interior_pressure,interior_cpu);double interior_sum=0;for(double q:interior_cpu)interior_sum+=q;std::printf("[paraglider] augmented EB composite: ready=%d storage=%d/%d edges=%zu sum=%.3e\n",interior_atlas.ready_for_flow()?1:0,interior_system.storage_size,regular_storage,interior_system.embedded.size(),interior_sum);check(interior_atlas.ready_for_flow()&&interior_system.storage_size>regular_storage&&!interior_system.embedded.empty()&&std::abs(interior_sum)<1e-11,"cross-brick EB fragments/apertures augment one conservative composite operator");std::vector<Real> interior_real(interior_system.storage_size),interior_gpu(interior_system.storage_size);for(int q=0;q<interior_system.storage_size;++q)interior_real[q]=(Real)interior_pressure[q];Real *interior_dp=nullptr,*interior_da=nullptr;cudaMalloc(&interior_dp,interior_real.size()*sizeof(Real));cudaMalloc(&interior_da,interior_real.size()*sizeof(Real));cudaMemcpy(interior_dp,interior_real.data(),interior_real.size()*sizeof(Real),cudaMemcpyHostToDevice);DeviceCompositeAmrPressureOperator interior_device(interior_system);interior_device.apply(interior_dp,interior_da);cudaMemcpy(interior_gpu.data(),interior_da,interior_gpu.size()*sizeof(Real),cudaMemcpyDeviceToHost);cudaFree(interior_dp);cudaFree(interior_da);double interior_error=0,interior_scale=1;for(int q=0;q<interior_system.storage_size;++q){interior_error=std::max(interior_error,std::abs((double)interior_gpu[q]-interior_cpu[q]));interior_scale=std::max(interior_scale,std::abs(interior_cpu[q]));}check(interior_error/interior_scale<(sizeof(Real)==4?3e-6:1e-12),"CUDA composite operator includes compact zero-thickness EB topology");
	AmrHostFields interior_transport_host(uh);for(auto& level:interior_transport_host.levels())std::fill(level.u.begin(),level.u.end(),Real(1));DeviceAmrFields interior_transport_fields(uh);interior_transport_fields.upload(interior_transport_host);DeviceCompositeAmrProjection interior_transport_projection(interior_system,interior_transport_fields);interior_transport_projection.initialize_special_freestream(Real(1));double expected_eb_cfl_rate=0;for(const CoarseFinePressureConnection& edge:interior_system.embedded)if(edge.axis==0){const double a=std::cbrt(interior_system.volume[edge.coarse_dof]),b=std::cbrt(interior_system.volume[edge.fine_dof]),length=std::max(edge.centre_distance,0.5*(a+b));expected_eb_cfl_rate=std::max(expected_eb_cfl_rate,1.0/length);}check(near(interior_transport_projection.max_embedded_cfl_rate(),expected_eb_cfl_rate,sizeof(Real)==4?2e-6:1e-12),"compact EB graph publishes its explicit CFL rate");interior_transport_projection.transport_embedded_apertures(Real(0.1),Real(0.01),Real(0.1));CompositeAmrFluxes interior_uniform_flux;interior_transport_projection.download_special_fluxes(interior_uniform_flux);bool eb_uniform=true;for(std::size_t edge=0;edge<interior_system.embedded.size();++edge)eb_uniform=eb_uniform&&near(interior_uniform_flux.embedded_velocity[edge],interior_system.embedded[edge].axis==0?1.0:0.0,sizeof(Real)==4?2e-6:1e-12);check(eb_uniform,"compact same-side transport preserves uniform freestream with graph LES");
	CompositeAmrFluxes interior_perturbed_flux=interior_uniform_flux;interior_perturbed_flux.embedded_velocity.front()=Real(2);if(interior_perturbed_flux.embedded_velocity.size()>1)interior_perturbed_flux.embedded_velocity[1]=Real(-1);interior_transport_projection.upload_special_fluxes(interior_perturbed_flux);interior_transport_projection.transport_embedded_apertures(Real(0.1),Real(0),Real(0));CompositeAmrFluxes interior_no_les;interior_transport_projection.download_special_fluxes(interior_no_les);interior_transport_projection.upload_special_fluxes(interior_perturbed_flux);interior_transport_projection.transport_embedded_apertures(Real(0.1),Real(0),Real(0.2));CompositeAmrFluxes interior_transported_flux;interior_transport_projection.download_special_fluxes(interior_transported_flux);auto perturbation_energy=[&](const CompositeAmrFluxes& flux){double energy=0;for(std::size_t edge=0;edge<interior_system.embedded.size();++edge){const double uniform=interior_system.embedded[edge].axis==0?1.0:0.0,difference=flux.embedded_velocity[edge]-uniform;energy+=interior_system.embedded[edge].open_area*difference*difference;}return energy;};const bool eb_evolved=std::isfinite(interior_transported_flux.embedded_velocity.front())&&!near(interior_transported_flux.embedded_velocity.front(),interior_perturbed_flux.embedded_velocity.front(),1e-7);const bool eb_distinct=interior_transported_flux.embedded_velocity.size()<2||!near(interior_transported_flux.embedded_velocity[0],interior_transported_flux.embedded_velocity[1],1e-7);bool eb_bounded=true;for(double velocity:interior_transported_flux.embedded_velocity)eb_bounded=eb_bounded&&velocity>=-1.000001&&velocity<=2.000001;check(eb_evolved&&eb_distinct,"compact EB apertures evolve as distinct fluid-connected velocity states with graph LES");check(eb_bounded,"compact EB transport cannot create a same-side stencil velocity extremum");check(perturbation_energy(interior_transported_flux)<perturbation_energy(interior_no_les),"compact graph Smagorinsky term dissipates a nonuniform aperture state");
	Real compact_shear_gradient[9]={};compact_shear_gradient[1]=Real(2);check(near(detail::compact_strain_magnitude_squared(compact_shear_gradient),4.0,sizeof(Real)==4?2e-6:1e-12),"compact strain formula includes tangential shear");
	Real compact_rotation_gradient[9]={};compact_rotation_gradient[1]=Real(2);compact_rotation_gradient[3]=Real(-2);check(near(detail::compact_strain_magnitude_squared(compact_rotation_gradient),0.0,sizeof(Real)==4?2e-6:1e-12),"compact strain formula excludes rigid rotation");
	Real compact_extension_gradient[9]={};compact_extension_gradient[0]=Real(2);check(near(detail::compact_strain_magnitude_squared(compact_extension_gradient),8.0,sizeof(Real)==4?2e-6:1e-12),"compact strain formula retains normal extension");
	auto& compact_shear_level=interior_transport_host.levels()[0];const BrickFieldLayout compact_shear_layout=compact_shear_level.layout;std::fill(compact_shear_level.u.begin(),compact_shear_level.u.end(),Real(0));std::fill(compact_shear_level.v.begin(),compact_shear_level.v.end(),Real(0));std::fill(compact_shear_level.w.begin(),compact_shear_level.w.end(),Real(0));for(int brick=0;brick<2;++brick)for(int k=0;k<4;++k)for(int j=0;j<4;++j)for(int i=0;i<=4;++i)compact_shear_level.u[compact_shear_layout.u_index(brick,i,j,k)]=Real(1+0.5*(j+0.5));interior_transport_fields.upload(interior_transport_host);CompositeAmrFluxes compact_shear_flux=make_zero_composite_fluxes(interior_system);int compact_shear_target=-1;for(std::size_t edge=0;edge<interior_system.embedded.size();++edge)if(interior_system.embedded[edge].axis==0){compact_shear_flux.embedded_velocity[edge]=1+0.5*interior_system.embedded[edge].face_centroid.y;if(compact_shear_target<0&&interior_system.embedded[edge].face_centroid.y>1&&interior_system.embedded[edge].face_centroid.y<3)compact_shear_target=static_cast<int>(edge);}check(compact_shear_target>=0,"compact shear fixture has an interior streamwise aperture");compact_shear_flux.embedded_velocity[compact_shear_target]+=0.5;interior_transport_projection.upload_special_fluxes(compact_shear_flux);interior_transport_projection.transport_embedded_apertures(Real(0.05),Real(0),Real(0));CompositeAmrFluxes compact_shear_no_les;interior_transport_projection.download_special_fluxes(compact_shear_no_les);interior_transport_projection.upload_special_fluxes(compact_shear_flux);interior_transport_projection.transport_embedded_apertures(Real(0.05),Real(0),Real(0.2));CompositeAmrFluxes compact_shear_les;interior_transport_projection.download_special_fluxes(compact_shear_les);double compact_shear_response=0;for(std::size_t edge=0;edge<compact_shear_les.embedded_velocity.size();++edge)compact_shear_response=std::max(compact_shear_response,std::abs(compact_shear_les.embedded_velocity[edge]-compact_shear_no_les.embedded_velocity[edge]));check(compact_shear_response>(sizeof(Real)==4?1e-6:1e-12),"compact CUDA graph-strain LES responds to tangential shear");
	const Real compact_quadratic=detail::bounded_compact_transport_update(Real(4),Real(2.5),Real(6.5),Real(1),Real(0),Real(9),Real(0.25),Real(0),true);check(near(compact_quadratic,3.0625,sizeof(Real)==4?2e-6:1e-12),"compact MUSCL reconstruction transports a smooth quadratic characteristic");
	AmrHierarchy muscl_h=AmrHierarchy::uniform({{0,0,0},{8,8,8}},1.0,8,1);TriMesh muscl_fabric=mesh_from_quads({{{{3.5,0,0},{3.5,8,0},{3.5,8,8},{3.5,0,8}}}});TriangleBvh muscl_bvh(muscl_fabric);AmrEmbeddedBoundaryAtlas muscl_atlas=build_amr_embedded_boundary_atlas(muscl_h,muscl_fabric,muscl_bvh);CompositeAmrPressureSystem muscl_system=build_composite_amr_pressure_system(muscl_h,muscl_atlas,false);AmrHostFields muscl_host(muscl_h);for(auto& level:muscl_host.levels()){std::fill(level.u.begin(),level.u.end(),Real(1));std::fill(level.v.begin(),level.v.end(),Real(1));std::fill(level.w.begin(),level.w.end(),Real(1));}DeviceAmrFields muscl_fields(muscl_h);muscl_fields.upload(muscl_host);DeviceCompositeAmrProjection muscl_projection(muscl_system,muscl_fields);CompositeAmrFluxes muscl_flux=make_zero_composite_fluxes(muscl_system);std::fill(muscl_flux.embedded_velocity.begin(),muscl_flux.embedded_velocity.end(),1.0);muscl_projection.upload_special_fluxes(muscl_flux);muscl_projection.transport_embedded_apertures(Real(0.1),Real(0.01),Real(0.1));muscl_projection.download_special_fluxes(muscl_flux);bool muscl_uniform=true;for(double velocity:muscl_flux.embedded_velocity)muscl_uniform=muscl_uniform&&near(velocity,1.0,sizeof(Real)==4?2e-6:1e-12);check(muscl_projection.embedded_high_order_stencil_count()>0&&muscl_uniform,"complete compact MUSCL chains preserve a uniform three-component state");
	std::vector<double> mapped_surface_pressure(interior_system.storage_size,0);double mapped_surface_area=0;for(const CompositeSurfacePressurePatch& patch:interior_system.surface_patches){mapped_surface_pressure[patch.plus_dof]=1;mapped_surface_pressure[patch.minus_dof]=3;mapped_surface_area+=patch.area;}AerodynamicLoads mapped_surface_load=compute_pressure_loads(interior_system,mapped_surface_pressure,interior_fabric.triangle_count(),fs,ar);check(near(mapped_surface_area,16.0,1e-10)&&near(mapped_surface_load.pressure_force.x,32.0,1e-9)&&near(mapped_surface_load.pressure_force.y,0)&&near(mapped_surface_load.pressure_force.z,0),"composite surface patches retain plus/minus pressure DOFs and CAD load mapping");
	check(project_composite_flux_case(interior_system,uh,true,"zero-thickness EB"),"coupled GPU projection removes EB aperture divergence");
	check(uh.locate_finest({6.2,1.2,2.2}).brick==1,"integer-coordinate finest-brick lookup");
	AmrHostFields hf(uh);auto& lf=hf.levels()[0];for(int br=0;br<2;++br)for(int k=0;k<4;++k)for(int j=0;j<4;++j)for(int i=0;i<4;++i)lf.p[lf.layout.cell_index(br,i,j,k)]=(Real)(10+10*br);std::vector<Real> mapped_pressure;gather_one_level_pressure(regular_composite,regular_composite_system,lf,mapped_pressure);const int mapped_left=regular_composite_system.cell_dof[regular_composite.topology.grid.cell_index(3,1,1)],mapped_right=regular_composite_system.cell_dof[regular_composite.topology.grid.cell_index(4,1,1)];check(near(mapped_pressure[mapped_left],10)&&near(mapped_pressure[mapped_right],20),"host bridge maps level-global EB pressure into pooled bricks");mapped_pressure[mapped_right]=Real(23);scatter_one_level_pressure(regular_composite,regular_composite_system,mapped_pressure,lf);check(near(lf.p[lf.layout.cell_index(1,0,1,1)],23),"host bridge scatters EB pressure into pooled bricks");lf.p[lf.layout.cell_index(1,0,1,1)]=Real(20);
	DeviceAmrFields df(uh);df.upload(hf);DeviceOneLevelPressureMap device_pressure_map(regular_composite,regular_composite_system);Real* device_mapped_pressure=nullptr;cudaMalloc(&device_mapped_pressure,mapped_pressure.size()*sizeof(Real));cudaMemset(device_mapped_pressure,0,mapped_pressure.size()*sizeof(Real));device_pressure_map.gather(df.pressure(0),device_mapped_pressure);cudaMemcpy(mapped_pressure.data(),device_mapped_pressure,mapped_pressure.size()*sizeof(Real),cudaMemcpyDeviceToHost);check(near(mapped_pressure[mapped_left],10)&&near(mapped_pressure[mapped_right],20),"CUDA bridge gathers pooled brick pressure without host field transfer");mapped_pressure[mapped_right]=Real(29);cudaMemcpy(device_mapped_pressure,mapped_pressure.data(),mapped_pressure.size()*sizeof(Real),cudaMemcpyHostToDevice);device_pressure_map.scatter(device_mapped_pressure,df.pressure(0));df.download_pressure(hf);cudaFree(device_mapped_pressure);check(near(lf.p[lf.layout.cell_index(1,0,1,1)],29),"CUDA bridge scatters composite pressure without host field transfer");lf.p[lf.layout.cell_index(1,0,1,1)]=Real(20);
	hf.exchange_same_level_pressure_halos(uh);check(near(lf.p[lf.layout.cell_index(0,4,2,2)],20),"same-level host halo exchange");
	lf.p[lf.layout.cell_index(0,4,2,2)]=0;df.upload(hf);df.exchange_same_level_pressure_halos();df.download_pressure(hf);check(near(hf.levels()[0].p[lf.layout.cell_index(0,4,2,2)],20),"same-level CUDA halo exchange");
	std::fill(lf.u.begin(),lf.u.end(),Real(0));std::fill(lf.v.begin(),lf.v.end(),Real(0));std::fill(lf.w.begin(),lf.w.end(),Real(0));std::fill(lf.p.begin(),lf.p.end(),Real(0));lf.p[lf.layout.cell_index(1,3,1,1)]=Real(3);lf.u[lf.layout.u_index(0,1,1,0)]=Real(7);lf.v[lf.layout.v_index(0,1,0,1)]=Real(5);lf.w[lf.layout.w_index(0,1,1,0)]=Real(5);df.upload(hf);df.apply_external_aero_boundaries(Real(10));df.download(hf);check(near(lf.u[lf.layout.u_index(0,0,1,1)],10)&&near(lf.p[lf.layout.cell_index(1,4,1,1)],-3)&&near(lf.u[lf.layout.u_index(0,1,1,-1)],7)&&near(lf.v[lf.layout.v_index(0,1,0,1)],0)&&near(lf.w[lf.layout.w_index(0,1,1,0)],0),"GPU external BC: +X inflow/outlet and free-slip Y/Z (no ground)");
	DeviceAmrFields uniform_advection_fields(uh);uniform_advection_fields.initialize_freestream(Real(2));DeviceAmrAdvection uniform_advection(uh,no_fabric_bvh);uniform_advection.advect(uniform_advection_fields,Real(0.2));uniform_advection.diffuse_smagorinsky(uniform_advection_fields,Real(1.5e-5),Real(0.1),Real(0.2));AmrHostFields uniform_advection_host(uh);uniform_advection_fields.download(uniform_advection_host);double uniform_advection_error=0,uniform_nut_max=0;for(int brick=0;brick<2;++brick)for(int k=0;k<4;++k)for(int j=0;j<4;++j){for(int i=0;i<=4;++i)uniform_advection_error=std::max(uniform_advection_error,std::abs(static_cast<double>(uniform_advection_host.levels()[0].u[uniform_advection_host.levels()[0].layout.u_index(brick,i,j,k)])-2.0));for(int i=0;i<4;++i)uniform_nut_max=std::max(uniform_nut_max,std::abs(static_cast<double>(uniform_advection_host.levels()[0].nut[uniform_advection_host.levels()[0].layout.cell_index(brick,i,j,k)])));}std::printf("[paraglider] uniform AMR advection/LES velocity error %.3e, nut max %.3e\n",uniform_advection_error,uniform_nut_max);check(uniform_advection_error<(sizeof(Real)==4?2e-6:1e-12)&&uniform_nut_max<(sizeof(Real)==4?2e-7:1e-13),"GPU AMR advection/Smagorinsky preserve uniform freestream");
	check(near(uniform_advection_fields.max_abs_velocity(),2.0,sizeof(Real)==4?2e-6:1e-12),"GPU pooled-field max-velocity reduction supports adaptive global CFL");
	AmrHierarchy conservative_h=AmrHierarchy::uniform({{0,0,0},{8,8,8}},1.0,8,1);AmrHostFields conservative_host(conservative_h);auto& conservative_level=conservative_host.levels()[0];for(int k=0;k<8;++k)for(int j=0;j<8;++j){conservative_level.u[conservative_level.layout.u_index(0,2,j,k)]=Real(0.5);conservative_level.u[conservative_level.layout.u_index(0,3,j,k)]=Real(1);conservative_level.u[conservative_level.layout.u_index(0,4,j,k)]=Real(0.75);conservative_level.u[conservative_level.layout.u_index(0,5,j,k)]=Real(0.25);}auto lattice_momentum=[](const AmrHostLevelFields& level){Vec3d sum{};for(int k=0;k<8;++k)for(int j=0;j<8;++j)for(int i=0;i<=8;++i)sum.x+=level.u[level.layout.u_index(0,i,j,k)];for(int k=0;k<8;++k)for(int j=0;j<=8;++j)for(int i=0;i<8;++i)sum.y+=level.v[level.layout.v_index(0,i,j,k)];for(int k=0;k<=8;++k)for(int j=0;j<8;++j)for(int i=0;i<8;++i)sum.z+=level.w[level.layout.w_index(0,i,j,k)];return sum;};const Vec3d conservative_before=lattice_momentum(conservative_level);DeviceAmrFields conservative_fields(conservative_h);conservative_fields.upload(conservative_host);DeviceAmrAdvection conservative_advection(conservative_h,no_fabric_bvh);conservative_advection.advect_conservative_uniform(conservative_fields,Real(0.2));conservative_fields.download(conservative_host);const Vec3d conservative_after=lattice_momentum(conservative_level);check(near(conservative_after.x,conservative_before.x,sizeof(Real)==4?2e-5:1e-12)&&near(conservative_after.y,conservative_before.y,sizeof(Real)==4?2e-5:1e-12)&&near(conservative_after.z,conservative_before.z,sizeof(Real)==4?2e-5:1e-12),"one-level finite-volume MAC advection conserves discrete momentum");
	for(auto& level:conservative_host.levels()){std::fill(level.u.begin(),level.u.end(),Real(1.25));std::fill(level.v.begin(),level.v.end(),Real(-0.5));std::fill(level.w.begin(),level.w.end(),Real(0.75));}conservative_fields.upload(conservative_host);conservative_advection.advect_conservative_uniform(conservative_fields,Real(0.2));conservative_fields.download(conservative_host);double conservative_constant_error=0;for(int k=0;k<8;++k)for(int j=0;j<8;++j)for(int i=0;i<=8;++i)conservative_constant_error=std::max(conservative_constant_error,std::abs(static_cast<double>(conservative_level.u[conservative_level.layout.u_index(0,i,j,k)])-1.25));for(int k=0;k<8;++k)for(int j=0;j<=8;++j)for(int i=0;i<8;++i)conservative_constant_error=std::max(conservative_constant_error,std::abs(static_cast<double>(conservative_level.v[conservative_level.layout.v_index(0,i,j,k)])+0.5));for(int k=0;k<=8;++k)for(int j=0;j<8;++j)for(int i=0;i<8;++i)conservative_constant_error=std::max(conservative_constant_error,std::abs(static_cast<double>(conservative_level.w[conservative_level.layout.w_index(0,i,j,k)])-0.75));check(conservative_constant_error<(sizeof(Real)==4?2e-6:1e-12),"one-level finite-volume MAC advection preserves a constant vector field");
	AmrHostFields conservative_bricks_host(uh);auto& conservative_bricks_level=conservative_bricks_host.levels()[0];for(int brick=0;brick<2;++brick)for(int k=0;k<4;++k)for(int j=0;j<4;++j)for(int i=0;i<=4;++i){const int global_i=4*brick+i;conservative_bricks_level.u[conservative_bricks_level.layout.u_index(brick,i,j,k)]=global_i==2?Real(0.5):(global_i==3?Real(1):(global_i==4?Real(0.75):(global_i==5?Real(0.25):Real(0))));}auto unique_two_brick_u=[&](const AmrHostLevelFields& level){double sum=0;for(int brick=0;brick<2;++brick)for(int k=0;k<4;++k)for(int j=0;j<4;++j)for(int i=0;i<=4;++i)if(!(i==0&&uh.levels()[0].bricks[brick].same_level_neighbor[0]>=0))sum+=level.u[level.layout.u_index(brick,i,j,k)];return sum;};const double conservative_bricks_before=unique_two_brick_u(conservative_bricks_level);DeviceAmrFields conservative_bricks_fields(uh);conservative_bricks_fields.upload(conservative_bricks_host);DeviceAmrAdvection conservative_bricks_advection(uh,no_fabric_bvh);conservative_bricks_advection.advect_conservative_uniform(conservative_bricks_fields,Real(0.2));conservative_bricks_fields.download(conservative_bricks_host);const double conservative_bricks_after=unique_two_brick_u(conservative_bricks_level),left_interface=conservative_bricks_level.u[conservative_bricks_level.layout.u_index(0,4,1,1)],right_interface=conservative_bricks_level.u[conservative_bricks_level.layout.u_index(1,0,1,1)];check(near(conservative_bricks_after,conservative_bricks_before,sizeof(Real)==4?2e-5:1e-12)&&near(left_interface,right_interface,sizeof(Real)==4?2e-6:1e-12),"one-level conservative MAC flux crosses a brick boundary once");
	AmrHostFields conservative_fabric_host(uh);auto& conservative_fabric_level=conservative_fabric_host.levels()[0];for(int k=0;k<4;++k)for(int j=0;j<4;++j){for(int i=1;i<=3;++i)conservative_fabric_level.u[conservative_fabric_level.layout.u_index(0,i,j,k)]=Real(1);for(int i=1;i<4;++i)for(int face_j=0;face_j<=4;++face_j)conservative_fabric_level.v[conservative_fabric_level.layout.v_index(0,i,face_j,k)]=Real(1);}auto fabric_tangential_momentum=[](const AmrHostLevelFields& level){double sum=0;for(int brick=0;brick<2;++brick)for(int k=0;k<4;++k)for(int j=0;j<=4;++j)for(int i=0;i<4;++i)sum+=level.v[level.layout.v_index(brick,i,j,k)];return sum;};const double conservative_fabric_before=fabric_tangential_momentum(conservative_fabric_level);DeviceAmrFields conservative_fabric_fields(uh);conservative_fabric_fields.upload(conservative_fabric_host);DeviceAmrAdvection conservative_fabric_advection(uh,interface_bvh,1.0);conservative_fabric_advection.advect_conservative_uniform(conservative_fabric_fields,Real(0.2));conservative_fabric_fields.download(conservative_fabric_host);const double conservative_fabric_after=fabric_tangential_momentum(conservative_fabric_level);double conservative_fabric_opposite=0;for(int k=0;k<4;++k)for(int j=0;j<=4;++j)for(int i=0;i<4;++i)conservative_fabric_opposite=std::max(conservative_fabric_opposite,std::abs(static_cast<double>(conservative_fabric_level.v[conservative_fabric_level.layout.v_index(1,i,j,k)])));std::printf("[paraglider] conservative fabric momentum %.9g -> %.9g, opposite max %.9g\n",conservative_fabric_before,conservative_fabric_after,conservative_fabric_opposite);check(near(conservative_fabric_after,conservative_fabric_before,sizeof(Real)==4?2e-5:1e-12)&&conservative_fabric_opposite<(sizeof(Real)==4?2e-6:1e-12),"one-level conservative MAC flux is pairwise and cannot cross fabric links");
	uniform_advection_host.levels()[0].u[uniform_advection_host.levels()[0].layout.u_index(0,-1,1,1)]=Real(200);uniform_advection_fields.upload(uniform_advection_host);check(near(uniform_advection_fields.max_abs_velocity(),2.0,sizeof(Real)==4?2e-6:1e-12),"adaptive CFL reduction excludes halo storage");
	// A linearly varying tangential velocity must interpolate through x=4 rather
	// than extend the right brick's first value into its backtrace stencil.
	AmrHostFields cross_brick_advect_host(uh);auto& cross_advect_level=cross_brick_advect_host.levels()[0];
	for(int brick=0;brick<2;++brick){const double ox=uh.levels()[0].bricks[brick].origin.x;for(int k=0;k<4;++k)for(int j=0;j<4;++j){for(int i=0;i<=4;++i)cross_advect_level.u[cross_advect_level.layout.u_index(brick,i,j,k)]=Real(1);for(int i=0;i<4;++i)cross_advect_level.v[cross_advect_level.layout.v_index(brick,i,j,k)]=Real(ox+i+0.5);}}
	DeviceAmrFields cross_brick_advect_fields(uh);cross_brick_advect_fields.upload(cross_brick_advect_host);DeviceAmrAdvection cross_brick_advection(uh,no_fabric_bvh);cross_brick_advection.advect(cross_brick_advect_fields,Real(0.25));cross_brick_advect_fields.download(cross_brick_advect_host);const double cross_advected_v=cross_advect_level.v[cross_advect_level.layout.v_index(1,0,1,1)];check(near(cross_advected_v,4.25,sizeof(Real)==4?2e-6:1e-12),"AMR backtrace interpolates across a same-level brick boundary");
	// A quadratic profile distinguishes bounded MacCormack from the diffusive first-order
	// sweep: at x=4.5 after a 0.25 m translation, its exact value is 4.25^2.
	AmrHostFields maccormack_host(uh);auto& maccormack_level=maccormack_host.levels()[0];
	for(int brick=0;brick<2;++brick){const double ox=uh.levels()[0].bricks[brick].origin.x;for(int k=0;k<4;++k)for(int j=0;j<=4;++j){for(int i=0;i<=4&&j<4;++i)maccormack_level.u[maccormack_level.layout.u_index(brick,i,j,k)]=Real(1);for(int i=0;i<4;++i){const double x=ox+i+0.5;maccormack_level.v[maccormack_level.layout.v_index(brick,i,j,k)]=Real(x*x);}}}
	DeviceAmrFields maccormack_fields(uh);maccormack_fields.upload(maccormack_host);DeviceAmrAdvection maccormack_advection(uh,no_fabric_bvh);maccormack_advection.advect(maccormack_fields,Real(0.25));maccormack_fields.download(maccormack_host);const double maccormack_v=maccormack_level.v[maccormack_level.layout.v_index(1,0,1,1)],quadratic_exact=4.25*4.25;check(std::abs(maccormack_v-quadratic_exact)<0.08,"bounded MacCormack improves a nonlinear profile across a brick boundary");
	// The Laplacian of u=x is exactly zero at the same interface. Brick-local
	// clamping used to create equal and opposite artificial diffusion there.
	AmrHostFields cross_brick_diffuse_host(uh);auto& cross_diffuse_level=cross_brick_diffuse_host.levels()[0];
	for(int brick=0;brick<2;++brick){const double ox=uh.levels()[0].bricks[brick].origin.x;for(int k=0;k<4;++k)for(int j=0;j<4;++j)for(int i=0;i<=4;++i)cross_diffuse_level.u[cross_diffuse_level.layout.u_index(brick,i,j,k)]=Real(ox+i);}
	DeviceAmrFields cross_brick_diffuse_fields(uh);cross_brick_diffuse_fields.upload(cross_brick_diffuse_host);DeviceAmrAdvection cross_brick_diffusion(uh,no_fabric_bvh);cross_brick_diffusion.diffuse_smagorinsky(cross_brick_diffuse_fields,Real(0.1),Real(0),Real(0.1));cross_brick_diffuse_fields.download(cross_brick_diffuse_host);const double diffuse_left=cross_diffuse_level.u[cross_diffuse_level.layout.u_index(0,4,1,1)],diffuse_right=cross_diffuse_level.u[cross_diffuse_level.layout.u_index(1,0,1,1)];check(near(diffuse_left,4,sizeof(Real)==4?2e-6:1e-12)&&near(diffuse_right,4,sizeof(Real)==4?2e-6:1e-12),"AMR diffusion preserves a linear field across a brick boundary");
	AmrHostFields protected_host(uh);for(int brick=0;brick<2;++brick){auto& level=protected_host.levels()[0];std::fill(level.u.begin()+brick*level.layout.u_stride,level.u.begin()+(brick+1)*level.layout.u_stride,brick?Real(9):Real(1));}DeviceAmrFields protected_fields(uh);protected_fields.upload(protected_host);DeviceAmrAdvection protected_advection(uh,interface_bvh,1.0);protected_advection.advect(protected_fields,Real(0.2));protected_fields.download(protected_host);check(protected_advection.protected_face_count()>0&&near(protected_host.levels()[0].u[protected_host.levels()[0].layout.u_index(1,0,1,1)],9,1e-7),"same-side link graph prevents opposite-side advection sampling");
	AmrHostFields same_side_host(uh);auto& same_side_level=same_side_host.levels()[0];for(int brick=0;brick<2;++brick)for(int k=0;k<4;++k)for(int j=0;j<4;++j){for(int i=0;i<4;++i)same_side_level.v[same_side_level.layout.v_index(brick,i,j,k)]=Real(k+0.5);for(int i=0;i<4;++i)same_side_level.w[same_side_level.layout.w_index(brick,i,j,k)]=Real(1);}DeviceAmrFields same_side_fields(uh);same_side_fields.upload(same_side_host);DeviceAmrAdvection same_side_advection(uh,interface_bvh,1.0);same_side_advection.advect(same_side_fields,Real(0.2));same_side_fields.download(same_side_host);const double same_side_value=same_side_level.v[same_side_level.layout.v_index(1,0,1,1)];std::printf("[paraglider] same-side membrane advection value %.9g (linear characteristic 1.3)\n",same_side_value);check(std::abs(same_side_value-1.3)<0.03,"same-side link graph transports tangential flow near a membrane");
	AmrHostFields curved_side_host(uh);auto& curved_side_level=curved_side_host.levels()[0];for(int brick=0;brick<2;++brick)for(int k=0;k<4;++k)for(int j=0;j<4;++j){for(int i=0;i<4;++i){const Real z=Real(k)+Real(0.5);curved_side_level.v[curved_side_level.layout.v_index(brick,i,j,k)]=Real(0.1)*z*z;}for(int i=0;i<4;++i)curved_side_level.w[curved_side_level.layout.w_index(brick,i,j,k)]=Real(1);}DeviceAmrFields curved_side_fields(uh);curved_side_fields.upload(curved_side_host);DeviceAmrAdvection curved_side_advection(uh,interface_bvh,1.0);curved_side_advection.advect(curved_side_fields,Real(0.2));curved_side_fields.download(curved_side_host);const double curved_side_value=curved_side_level.v[curved_side_level.layout.v_index(1,0,1,2)],curved_exact=0.1*2.3*2.3;std::printf("[paraglider] limited same-side quadratic value %.9g (characteristic %.9g)\n",curved_side_value,curved_exact);check(std::abs(curved_side_value-curved_exact)<0.005,"limited same-side reconstruction improves smooth tangential transport");

	// Static refinement stays 2:1 and point lookup resolves a fine brick near the membrane.
	AmrConfig ac;ac.base_cell_size=0.5;ac.max_levels=3;ac.brick_size=4;ac.surface_refinement_distance=0.1;ac.wing_refinement_distance=0.2;ac.wake_length=1;ac.wake_radius=0.5;AmrHierarchy ah=AmrHierarchy::build_static({{-1,-1,-1},{3,3,3}},flat,bvh,ac);
	check(ah.levels().size()==3&&ah.is_two_to_one_balanced(),"static AMR hierarchy is 2:1 balanced");check(ah.locate_finest({0.5,0.5,0.5}).level==2,"surface region reaches configured finest level");
	DeviceAmrFields multilevel_advection_fields(ah);multilevel_advection_fields.initialize_freestream(Real(1.5));DeviceAmrAdvection multilevel_advection(ah,no_fabric_bvh);multilevel_advection.advect(multilevel_advection_fields,Real(0.05));AmrHostFields multilevel_advection_host(ah);multilevel_advection_fields.download(multilevel_advection_host);double multilevel_advection_error=0;for(std::size_t level=0;level<ah.levels().size();++level)for(int brick=0;brick<static_cast<int>(ah.levels()[level].bricks.size());++brick)if(ah.levels()[level].bricks[brick].active())for(int k=0;k<4;++k)for(int j=0;j<4;++j)for(int i=0;i<=4;++i)multilevel_advection_error=std::max(multilevel_advection_error,std::abs(static_cast<double>(multilevel_advection_host.levels()[level].u[multilevel_advection_host.levels()[level].layout.u_index(brick,i,j,k)])-1.5));check(multilevel_advection_error<(sizeof(Real)==4?2e-6:1e-12),"finest-brick AMR advection sampling preserves constant state across 2:1 hierarchy");
	AmrHostFields linear_cross_level_host(ah);
	for(std::size_t level=0;level<ah.levels().size();++level)
	{
		auto& field=linear_cross_level_host.levels()[level];const int bs=ah.brick_size();
		for(int brick=0;brick<static_cast<int>(ah.levels()[level].bricks.size());++brick)
		{
			const auto& metadata=ah.levels()[level].bricks[brick];
			for(int k=0;k<bs;++k)for(int j=0;j<bs;++j)for(int i=0;i<=bs;++i)field.u[field.layout.u_index(brick,i,j,k)]=Real(1);
			for(int k=0;k<bs;++k)for(int j=0;j<=bs;++j)for(int i=0;i<bs;++i)field.v[field.layout.v_index(brick,i,j,k)]=static_cast<Real>(metadata.origin.x+(i+0.5)*metadata.h);
		}
	}
	DeviceAmrFields linear_cross_level_fields(ah);linear_cross_level_fields.upload(linear_cross_level_host);DeviceAmrAdvection linear_cross_level_advection(ah,no_fabric_bvh);const Real linear_dt=Real(0.05);linear_cross_level_advection.advect(linear_cross_level_fields,linear_dt);linear_cross_level_fields.download(linear_cross_level_host);double linear_cross_level_error=0;std::size_t linear_cross_level_samples=0;int worst_level=-1,worst_brick=-1,worst_i=-1,worst_j=-1,worst_k=-1,worst_lower=-1,worst_upper=-1;double worst_value=0,worst_exact=0;
	for(std::size_t level=0;level<ah.levels().size();++level)
	{
		const auto& field=linear_cross_level_host.levels()[level];const int bs=ah.brick_size();
		for(int brick=0;brick<static_cast<int>(ah.levels()[level].bricks.size());++brick)if(ah.levels()[level].bricks[brick].active())
		{
			const auto& metadata=ah.levels()[level].bricks[brick];
			for(int k=0;k<bs;++k)for(int j=0;j<=bs;++j)for(int i=0;i<bs;++i)
			{
				const Vec3d point{metadata.origin.x+(i+0.5)*metadata.h,metadata.origin.y+j*metadata.h,metadata.origin.z+(k+0.5)*metadata.h};
				if(point.x-ah.domain().lo.x<2*metadata.h||ah.domain().hi.x-point.x<2*metadata.h)continue;
				const BrickLocation owner=ah.locate_finest(point);if(!owner.found()||owner.level!=static_cast<int>(level))continue;
				const BrickLocation lower=ah.locate_finest({point.x-0.51*metadata.h,point.y,point.z}),upper=ah.locate_finest({point.x+0.51*metadata.h,point.y,point.z});
				if(!lower.found()||!upper.found()||(lower.level==static_cast<int>(level)&&upper.level==static_cast<int>(level)))continue;
				const double value=field.v[field.layout.v_index(brick,i,j,k)],exact=point.x-static_cast<double>(linear_dt);
				const double error=std::abs(value-exact);if(error>linear_cross_level_error){linear_cross_level_error=error;worst_level=static_cast<int>(level);worst_brick=brick;worst_i=i;worst_j=j;worst_k=k;worst_lower=lower.level;worst_upper=upper.level;worst_value=value;worst_exact=exact;}++linear_cross_level_samples;
			}
		}
	}
	// GPU AMR locations and brick metadata intentionally remain FP32 in both field modes,
	// so the FP64 validation build retains the coordinate-rounding floor seen here.
	const double cross_level_coordinate_tolerance=5e-7;
	std::printf("[paraglider] linear 2:1 advection: samples=%zu max error=%.3e value/exact=%.9g/%.9g level/brick/ijk=%d/%d/[%d %d %d] neighbours=%d/%d\n",linear_cross_level_samples,linear_cross_level_error,worst_value,worst_exact,worst_level,worst_brick,worst_i,worst_j,worst_k,worst_lower,worst_upper);check(linear_cross_level_samples>0&&linear_cross_level_error<cross_level_coordinate_tolerance,"2:1 interpolation preserves a linear tangential characteristic");
	linear_cross_level_advection.diffuse_smagorinsky(linear_cross_level_fields,Real(0.1),Real(0),Real(0.01));linear_cross_level_fields.download(linear_cross_level_host);double linear_cross_level_diffusion_error=0;std::size_t linear_cross_level_diffusion_samples=0;
	for(std::size_t level=0;level<ah.levels().size();++level)
	{
		const auto& field=linear_cross_level_host.levels()[level];const int bs=ah.brick_size();
		for(int brick=0;brick<static_cast<int>(ah.levels()[level].bricks.size());++brick)if(ah.levels()[level].bricks[brick].active())
		{
			const auto& metadata=ah.levels()[level].bricks[brick];
			for(int k=0;k<bs;++k)for(int j=0;j<=bs;++j)for(int i=0;i<bs;++i)
			{
				const Vec3d point{metadata.origin.x+(i+0.5)*metadata.h,metadata.origin.y+j*metadata.h,metadata.origin.z+(k+0.5)*metadata.h};const BrickLocation owner=ah.locate_finest(point);if(!owner.found()||owner.level!=static_cast<int>(level))continue;const BrickLocation lower=ah.locate_finest({point.x-0.51*metadata.h,point.y,point.z}),upper=ah.locate_finest({point.x+0.51*metadata.h,point.y,point.z});if(!lower.found()||!upper.found()||(lower.level==static_cast<int>(level)&&upper.level==static_cast<int>(level)))continue;const double value=field.v[field.layout.v_index(brick,i,j,k)],exact=point.x-static_cast<double>(linear_dt);linear_cross_level_diffusion_error=std::max(linear_cross_level_diffusion_error,std::abs(value-exact));++linear_cross_level_diffusion_samples;
			}
		}
	}
	std::printf("[paraglider] linear 2:1 diffusion: samples=%zu max error=%.3e\n",linear_cross_level_diffusion_samples,linear_cross_level_diffusion_error);check(linear_cross_level_diffusion_samples>0&&linear_cross_level_diffusion_error<cross_level_coordinate_tolerance,"2:1 diffusion preserves a linear tangential field");
	CompositeAmrPressureSystem composite_amr=build_composite_amr_pressure_system(ah,false);check(!composite_amr.coarse_fine.empty()&&composite_amr.coarse_fine.size()%4==0,"composite AMR stores only compact 2:1 interface connections");bool interface_tiles=true;for(std::size_t edge=0;edge<composite_amr.coarse_fine.size();edge+=4){double tile_area=0;const int coarse_dof=composite_amr.coarse_fine[edge].coarse_dof;for(int tile=0;tile<4;++tile){const auto& connection=composite_amr.coarse_fine[edge+tile];tile_area+=connection.open_area;interface_tiles=interface_tiles&&connection.coarse_dof==coarse_dof;}const double fine_h=std::sqrt(composite_amr.coarse_fine[edge].open_area);interface_tiles=interface_tiles&&near(tile_area,4*fine_h*fine_h,1e-13);}check(interface_tiles,"four fine apertures exactly tile each coarse AMR face");
	AmrHostFields coarse_fine_transport_host(ah);for(auto& level:coarse_fine_transport_host.levels()){std::fill(level.u.begin(),level.u.end(),Real(1.25));std::fill(level.v.begin(),level.v.end(),Real(-0.5));std::fill(level.w.begin(),level.w.end(),Real(0.75));}DeviceAmrFields coarse_fine_transport_fields(ah);coarse_fine_transport_fields.upload(coarse_fine_transport_host);DeviceCompositeAmrProjection coarse_fine_transport_projection(composite_amr,coarse_fine_transport_fields);coarse_fine_transport_projection.sync_coarse_fine_from_fields();CompositeAmrFluxes coarse_fine_transport_flux;coarse_fine_transport_projection.download_special_fluxes(coarse_fine_transport_flux);bool gathered_tiles=true;for(std::size_t edge=0;edge<composite_amr.coarse_fine.size();++edge){const int axis=composite_amr.coarse_fine[edge].axis;const double expected=axis==0?1.25:(axis==1?-0.5:0.75);gathered_tiles=gathered_tiles&&near(coarse_fine_transport_flux.coarse_fine_velocity[edge],expected,sizeof(Real)==4?2e-6:1e-12);}check(gathered_tiles,"2:1 compact velocities gather from collocated fine MAC faces");
	for(std::size_t edge=0;edge<coarse_fine_transport_flux.coarse_fine_velocity.size();++edge)coarse_fine_transport_flux.coarse_fine_velocity[edge]=0.25+0.125*(edge%4);coarse_fine_transport_projection.upload_special_fluxes(coarse_fine_transport_flux);coarse_fine_transport_projection.correct_fluxes(Real(1),Real(0.1));coarse_fine_transport_projection.sync_coarse_fine_from_fields();CompositeAmrFluxes coarse_fine_roundtrip;coarse_fine_transport_projection.download_special_fluxes(coarse_fine_roundtrip);bool fine_roundtrip=true;for(std::size_t edge=0;edge<coarse_fine_transport_flux.coarse_fine_velocity.size();++edge)fine_roundtrip=fine_roundtrip&&near(coarse_fine_roundtrip.coarse_fine_velocity[edge],coarse_fine_transport_flux.coarse_fine_velocity[edge],sizeof(Real)==4?2e-6:1e-12);check(fine_roundtrip,"projected 2:1 tile velocities scatter back to fine MAC faces");
	coarse_fine_transport_fields.download(coarse_fine_transport_host);bool coarse_flux_mean=true;const int cf_cells=ah.brick_size()*ah.brick_size()*ah.brick_size();for(std::size_t edge=0;edge<composite_amr.coarse_fine.size();edge+=4){const auto& connection=composite_amr.coarse_fine[edge];int level=-1,brick=-1,local=-1;for(int candidate=0;candidate<(int)ah.levels().size();++candidate){const int begin=composite_amr.level_offset[candidate],end=begin+(int)ah.levels()[candidate].bricks.size()*cf_cells;if(connection.coarse_dof>=begin&&connection.coarse_dof<end){level=candidate;const int work=connection.coarse_dof-begin;brick=work/cf_cells;local=work%cf_cells;break;}}if(level<0){coarse_flux_mean=false;continue;}int i=local%ah.brick_size(),j=(local/ah.brick_size())%ah.brick_size(),k=local/(ah.brick_size()*ah.brick_size());if(connection.axis==0)i+=connection.direction>0;else if(connection.axis==1)j+=connection.direction>0;else k+=connection.direction>0;const auto& field=coarse_fine_transport_host.levels()[level];const double coarse_value=connection.axis==0?field.u[field.layout.u_index(brick,i,j,k)]:(connection.axis==1?field.v[field.layout.v_index(brick,i,j,k)]:field.w[field.layout.w_index(brick,i,j,k)]);double flux=0,area_sum=0;for(int tile=0;tile<4;++tile){flux+=coarse_fine_transport_flux.coarse_fine_velocity[edge+tile]*composite_amr.coarse_fine[edge+tile].open_area;area_sum+=composite_amr.coarse_fine[edge+tile].open_area;}coarse_flux_mean=coarse_flux_mean&&near(coarse_value,flux/area_sum,sizeof(Real)==4?2e-6:1e-12);}check(coarse_flux_mean,"coarse 2:1 MAC face is the aperture-weighted fine velocity mean");
	check(project_composite_flux_case(composite_amr,ah,false,"2:1 AMR"),"coupled GPU projection removes coarse/fine divergence");
	std::vector<double> composite_amr_p(composite_amr.storage_size),composite_amr_cpu;for(int q=0;q<composite_amr.storage_size;++q)if(composite_amr.active[q])composite_amr_p[q]=0.003*q-0.7;composite_amr.apply_cpu(composite_amr_p,composite_amr_cpu);double composite_sum=0;for(double q:composite_amr_cpu)composite_sum+=q;check(std::abs(composite_sum)<1e-10,"composite multilevel pressure flux is globally conservative");std::vector<Real> composite_amr_real(composite_amr.storage_size),composite_amr_gpu(composite_amr.storage_size),composite_amr_rhs(composite_amr.storage_size);for(int q=0;q<composite_amr.storage_size;++q){composite_amr_real[q]=(Real)composite_amr_p[q];composite_amr_rhs[q]=(Real)composite_amr_cpu[q];}Real *composite_amr_dp=nullptr,*composite_amr_da=nullptr;cudaMalloc(&composite_amr_dp,composite_amr_real.size()*sizeof(Real));cudaMalloc(&composite_amr_da,composite_amr_real.size()*sizeof(Real));cudaMemcpy(composite_amr_dp,composite_amr_real.data(),composite_amr_real.size()*sizeof(Real),cudaMemcpyHostToDevice);DeviceCompositeAmrPressureOperator composite_amr_device(composite_amr);composite_amr_device.apply(composite_amr_dp,composite_amr_da);cudaMemcpy(composite_amr_gpu.data(),composite_amr_da,composite_amr_gpu.size()*sizeof(Real),cudaMemcpyDeviceToHost);double composite_amr_error=0,composite_amr_scale=1;for(int q=0;q<composite_amr.storage_size;++q){composite_amr_error=std::max(composite_amr_error,std::abs((double)composite_amr_gpu[q]-composite_amr_cpu[q]));composite_amr_scale=std::max(composite_amr_scale,std::abs(composite_amr_cpu[q]));}check(composite_amr_error/composite_amr_scale<(sizeof(Real)==4?3e-6:1e-12),"CUDA composite AMR operator matches CPU reference");cudaMemcpy(composite_amr_da,composite_amr_rhs.data(),composite_amr_rhs.size()*sizeof(Real),cudaMemcpyHostToDevice);DeviceCompositeAmrPressureSolver composite_amr_solver(composite_amr);AmrGpuSolveResult composite_solve=composite_amr_solver.solve(composite_amr_dp,composite_amr_da,sizeof(Real)==4?1e-5:1e-10,1000,false);std::printf("[paraglider] composite AMR GPU CG iterations=%d relative-residual=%.3e\n",composite_solve.iterations,composite_solve.relative_residual);check(composite_solve.converged,"one coupled GPU pressure solve spans every AMR level");cudaFree(composite_amr_dp);cudaFree(composite_amr_da);
	DeviceAmrLocator locator(ah);std::vector<GpuAmrPoint> locator_points{{0.5f,0.5f,0.5f},{-2.0f,-2.0f,-2.0f}};std::vector<GpuBrickLocation> locator_result(2);GpuAmrPoint* device_locator_points=nullptr;GpuBrickLocation* device_locator_result=nullptr;cudaMalloc(&device_locator_points,locator_points.size()*sizeof(GpuAmrPoint));cudaMalloc(&device_locator_result,locator_result.size()*sizeof(GpuBrickLocation));cudaMemcpy(device_locator_points,locator_points.data(),locator_points.size()*sizeof(GpuAmrPoint),cudaMemcpyHostToDevice);locator.locate_points(device_locator_points,device_locator_result,(int)locator_points.size());cudaMemcpy(locator_result.data(),device_locator_result,locator_result.size()*sizeof(GpuBrickLocation),cudaMemcpyDeviceToHost);cudaFree(device_locator_points);cudaFree(device_locator_result);check(locator_result[0].level==2&&locator_result[0].brick>=0&&locator_result[1].brick<0,"GPU hash locates finest brick without tree traversal");
	FluxMatchResult fm=match_two_to_one_flux(0.7,1.0,{1.0,2.0,3.0,4.0},{0.25,0.20,0.15,0.10});check(near(fm.corrected_coarse_velocity,fm.fine_flux_sum,1e-14)&&near(fm.corrected_coarse_velocity,fm.fine_flux_sum,1e-14),"AMR coarse flux equals aperture-weighted fine sum");
	AmrHostFields ahf(ah);int covered_parent=-1;for(int q=0;q<(int)ah.levels()[0].bricks.size();++q)if(!ah.levels()[0].bricks[q].active()){covered_parent=q;break;}if(covered_parent>=0){auto& cp=ahf.levels()[0];for(int k=0;k<ah.brick_size();++k)for(int j=0;j<ah.brick_size();++j)for(int i=0;i<ah.brick_size();++i)cp.p[cp.layout.cell_index(covered_parent,i,j,k)]=(Real)3.25;prolong_coarse_pressure_to_fine(ah,ahf,1);restrict_fine_pressure_to_coarse(ah,ahf,1);}check(covered_parent>=0&&near(ahf.levels()[0].p[ahf.levels()[0].layout.cell_index(covered_parent,1,1,1)],3.25,1e-7),"AMR prolongation/restriction conserves cell mean");

	ParagliderConfig cfg;std::string err;check(load_paraglider_config("configs/paraglider.json",cfg,&err)&&near(cfg.freestream.speed,10)&&cfg.amr.brick_size==32&&cfg.amr.complex_subdivisions==4&&near(cfg.amr.min_volume_fraction,0.25)&&near(cfg.amr.min_aperture_area_fraction,1e-4),"paraglider configuration schema/default");
	ParagliderConfig core_config;core_config.domain={1,3,1,1};core_config.amr.base_cell_size=1;core_config.amr.max_levels=1;core_config.amr.brick_size=4;core_config.amr.ghost_cells=1;core_config.amr.complex_subdivisions=8;core_config.solver.cfl=0.2;core_config.solver.projection_tolerance=sizeof(Real)==4?1e-5:1e-10;core_config.solver.projection_max_iterations=500;core_config.freestream.speed=1;core_config.freestream.rho=1;TriangleBvh core_plate_bvh(flat);ExternalAeroCore external_core(flat,core_plate_bvh,core_config);ExternalAeroStepStats initialization=external_core.initialize();ExternalAeroStepStats external_step=initialization.pressure.converged?external_core.step():ExternalAeroStepStats{};AerodynamicLoads external_load=external_core.pressure_loads();check(initialization.pressure.converged&&external_step.pressure.converged&&external_step.les_applied&&external_step.embedded_transport_applied&&external_core.physical_time()>0&&external_core.gpu_bytes()>0&&std::isfinite(external_load.pressure_force.x),"external-aero core initializes, transports regular/EB velocity, projects, and publishes pressure loads");

	std::printf("[paraglider] geometry/topology probe: %s (%d failures)\n",failures?"FAIL":"PASS",failures);return failures?1:0;
}
